NOISSUE - Remove vendor dir
absmach/coap-cli pull request #10
Opened 2024-04-24 08:15 UTC by 1998-felix

# What type of PR is this?
This is a dependency update as it removes the vendor directory.

## What does this do?
Removes vendor directory and modifys build mode to match this change.

## Which issue(s) does this PR fix/relate to?
None

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
N/A

### Notes
None

Signed-off-by:  [1998-felix](mailto:felix.gateru@gmail.com)

2024-04-24 08:19 UTC, rodneyosodo requested changes

2024-04-24 08:19 UTC, rodneyosodo commented on Makefile
> +	CGO_ENABLED=0 GOOS=windows go build -ldflags "-s -w" -o build/coap-cli-windows cmd/main.go
Add a new line

2024-04-24 08:20 UTC, rodneyosodo requested changes

2024-04-24 08:20 UTC, rodneyosodo commented on go.mod
>  module github.com/mainflux/coap-cli
Fix module name

2024-04-24 13:16 UTC, rodneyosodo requested changes

2024-04-24 13:16 UTC, rodneyosodo commented on go.mod
> +go 1.21
```suggestion
go 1.22
```

2024-04-24 13:24 UTC, rodneyosodo approved these changes
LGTM

2024-04-29 08:50 UTC, dborovcanin approved these changes

2024-04-29 08:50 UTC, merged