NOISSUE  - Add dtls config to  CoAP cli
absmach/coap-cli pull request #7
Opened 2023-09-27 04:12 UTC by 1998-felix

### What does this do?
Add dtls config to CoAP cli

### Which issue(s) does this PR fix/relate to?
No

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-10-09 12:44 UTC, dborovcanin requested changes

2023-10-09 12:44 UTC, dborovcanin commented on cert_utility/utility.go
> +	kb, err := os.Open("../certs/client.key")
Use `os.ReadFile` and make file paths configurable.

2023-10-09 12:44 UTC, dborovcanin commented on coap/client.go
> +func New(addr string, to_dtls bool) (Client, error) {
Avoid using snake_case. Also, use `switch` instead of `if-else`.

2023-10-09 12:44 UTC, dborovcanin commented on coap/client.go
> +	cert_utility "github.com/mainflux/coap-cli/cert_utility"
Rename to `certutil`.

2023-10-09 12:44 UTC, dborovcanin commented on coap/client.go
> +func New(addr string, to_dtls bool) (Client, error) {
Try using cert and key paths to determine DTLS. If the cert path is set, try establishing DTLS connection with cert on that path.

2023-10-12 08:43 UTC, rodneyosodo requested changes

2023-10-12 08:43 UTC, rodneyosodo commented on README.md
> +|tls   | dtls support                                   | false            |
align

2023-10-12 08:43 UTC, rodneyosodo commented on README.md
> +coap-cli get channels/0bb5ba61-a66e-4972-bab6-26f19962678f/messages/subtopic -auth 1e1017e6-dee7-45b4-8a13-00e6afeb66eb -o -tls
Add seperate example for dtls

2023-10-12 08:43 UTC, rodneyosodo commented on cert_utility/utility.go
> +package cert_utility
Rename package name to follow guidelines https://go.dev/blog/package-names

2023-10-12 08:43 UTC, rodneyosodo commented on coap/client.go
> +func (c Client) Receive(path string, opts ...message.Option) (interface {
Declare the returned interface somewhere first for readability

2023-10-12 09:11 UTC, SammyOina requested changes

2023-10-12 09:11 UTC, SammyOina commented on cert_utility/utility.go
> +	kb.Read(clientKeyBytes)
handle errors

2023-10-12 09:11 UTC, SammyOina commented on cmd/main.go
> +		c := make(chan os.Signal, 1) // make the channel buffered
remove comment

2023-10-12 09:11 UTC, SammyOina commented on cmd/main.go
> +	errs := make(chan error, 1) // make the channel buffered
remove comment

2023-10-23 13:22 UTC, SammyOina requested changes

2023-10-23 13:22 UTC, SammyOina commented on coap/client.go
> +}, error) {
```suggestion
func (c Client) Receive(path string, opts ...message.Option) (client.Observation, error) {
```

2023-10-24 17:31 UTC, felixgateru commented on coap/client.go
> +}, error) {
I dont think the Conn type has an implementation of Observation.

2025-09-05 11:07 UTC, rodneyosodo commented
@dborovcanin  Should we close this one in favour of https://github.com/absmach/coap-cli/pull/11?

2025-09-05 11:30 UTC, dborovcanin commented
Closing in favor of #11.

2025-09-05 11:30 UTC, closed without merging